# Generated by Django 6.0.5 on 2026-05-11 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_language_alter_patient_payment_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(default='Oak & Vine Health Center', max_length=200)),
                ('welcome_message', models.TextField(default='Book your appointment online. We will confirm within 24 hours.')),
                ('welcome_message_es', models.TextField(default='Reserve su cita en linea. Confirmaremos en menos de 24 horas.')),
                ('show_new_patient', models.BooleanField(default=True)),
                ('show_followup', models.BooleanField(default=True)),
                ('show_annual_exam', models.BooleanField(default=True)),
                ('show_urgent', models.BooleanField(default=True)),
                ('show_telemedicine', models.BooleanField(default=True)),
                ('available_slots_monday', models.CharField(blank=True, default='9:30,10:00,10:30,11:00,11:30,12:00,12:30,13:00,13:30,14:00', max_length=500)),
                ('available_slots_tuesday', models.CharField(blank=True, default='', help_text='Leave empty = by appointment only', max_length=500)),
                ('available_slots_wednesday', models.CharField(blank=True, default='9:30,10:00,10:30,11:00,11:30,12:00,12:30,13:00,13:30,14:00', max_length=500)),
                ('available_slots_thursday', models.CharField(blank=True, default='9:30,10:00,10:30,11:00,11:30,12:00,12:30,13:00,13:30,14:00', max_length=500)),
                ('available_slots_friday', models.CharField(blank=True, default='', help_text='Leave empty = by appointment only', max_length=500)),
                ('available_slots_saturday', models.CharField(blank=True, default='', help_text='Leave empty = by appointment only', max_length=500)),
                ('min_days_ahead', models.IntegerField(default=1, help_text='Minimum days in advance to book')),
                ('max_days_ahead', models.IntegerField(default=30, help_text='Maximum days ahead patients can book')),
                ('accepting_new_patients', models.BooleanField(default=True)),
                ('require_phone', models.BooleanField(default=True)),
                ('require_email', models.BooleanField(default=False)),
                ('notify_email', models.EmailField(blank=True, default='admin@oakvine.com', help_text='Email to notify when new booking arrives', max_length=254)),
                ('booking_enabled', models.BooleanField(default=True, help_text='Turn off to disable online booking completely')),
                ('offline_message', models.TextField(blank=True, default='Online booking is temporarily unavailable. Please call us.')),
            ],
            options={
                'verbose_name': 'Booking Configuration',
            },
        ),
        migrations.AlterField(
            model_name='appointment',
            name='visit_type',
            field=models.CharField(choices=[('new', 'New Patient'), ('followup', 'Follow Up'), ('annual', 'Annual Exam'), ('urgent', 'Urgent Visit'), ('telemedicine', 'Telemedicine')], default='new', max_length=20),
        ),
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('language', models.CharField(choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=2)),
                ('is_new_patient', models.BooleanField(default=True)),
                ('requested_date', models.DateField()),
                ('requested_time', models.CharField(max_length=10)),
                ('visit_type', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('converted', 'Converted to Appointment')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('converted_to_appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_request', to='patients.appointment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
