# Generated by Django 6.0.5 on 2026-05-18 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_patientactivity'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bookinglog',
            new_name='patients_bo_booking_6ddb74_idx',
            old_name='patients_bo_booking_235fa1_idx',
        ),
        migrations.RenameIndex(
            model_name='patientactivity',
            new_name='patients_pa_patient_7ed10a_idx',
            old_name='patients_pa_patient_14868f_idx',
        ),
        migrations.AddField(
            model_name='appointment',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
